name: terminal_project
description: Application for terminal which uses qr-code generation


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  easy_localization: ^3.0.1
  shared_preferences: ^2.0.15
  flag: ^6.0.0
  equatable: ^2.0.5
  flutter_svg: ^1.1.6
  build_runner: ^2.3.3
  dio: ^4.0.6
  retrofit: ^3.3.1
  flutter_secure_storage: ^8.0.0
  dartz: ^0.10.1
  another_brother: ^0.0.30
  permission_handler: ^10.2.0
  path_provider: ^2.0.13
  bluetooth_print: ^4.3.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^4.2.0





flutter:
  uses-material-design: true


  assets:
  - assets/images/
  - assets/fonts/
  - assets/translations/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

