name: terminal_project
description: Application for terminal which uses qr-code generation


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  easy_localization: ^3.0.1
  shared_preferences: ^2.0.15
  flag: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:
  uses-material-design: true


  assets:
  - assets/images/
  - assets/fonts/
  - assets/translations/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

